# 기존 NFS PVC는 보존됨 (helm.sh/resource-policy: keep 덕분에 삭제되지 않음)
# 이름: gitea-shared-storage, storageClass: nfs-client

# 새로운 Longhorn PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-shared-storage
  namespace: gitea
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 16Gi
